exports.trad = {
	"ability": [
		{"en": "Stench", "it": "Tanfo"},
		{"en": "Drizzle", "it": "Piovischio"},
		{"en": "Speed Boost", "it": "Acceleratore"},
		{"en": "Battle Armor", "it": "Lottascudo"},
		{"en": "Sturdy", "it": "Vigore"},
		{"en": "Damp", "it": "Umidità"},
		{"en": "Limber", "it": "Scioltezza"},
		{"en": "Sand Veil", "it": "Sabbiavelo"},
		{"en": "Static", "it": "Statico"},
		{"en": "Volt Absorb", "it": "Assorbivolt"},
		{"en": "Water Absorb", "it": "Assorbacqua"},
		{"en": "Oblivious", "it": "Indifferenza"},
		{"en": "Cloud Nine", "it": "Antimeteo"},
		{"en": "Compound Eyes", "it": "Insettocchi"},
		{"en": "Insomnia", "it": "Insonnia"},
		{"en": "Color Change", "it": "Cambiacolore"},
		{"en": "Immunity", "it": "Immunità"},
		{"en": "Flash Fire", "it": "Fuocardore"},
		{"en": "Shield Dust", "it": "Polvoscudo"},
		{"en": "Own Tempo", "it": "Mente Locale"},
		{"en": "Suction Cups", "it": "Ventose"},
		{"en": "Intimidate", "it": "Prepotenza"},
		{"en": "Shadow Tag", "it": "Pedinombra"},
		{"en": "Rough Skin", "it": "Cartavetro"},
		{"en": "Wonder Guard", "it": "Magidifesa"},
		{"en": "Levitate", "it": "Levitazione"},
		{"en": "Effect Spore", "it": "Spargispora"},
		{"en": "Synchronize", "it": "Sincronismo"},
		{"en": "Clear Body", "it": "Corpochiaro"},
		{"en": "Natural Cure", "it": "Alternacura"},
		{"en": "Lightning Rod", "it": "Parafulmine"},
		{"en": "Serene Grace", "it": "Leggiadro"},
		{"en": "Swift Swim", "it": "Nuotovelox"},
		{"en": "Chlorophyll", "it": "Clorofilla"},
		{"en": "Illuminate", "it": "Risplendi"},
		{"en": "Trace", "it": "Traccia"},
		{"en": "Huge Power", "it": "Macroforza"},
		{"en": "Poison Point", "it": "Velenopunto"},
		{"en": "Inner Focus", "it": "Fuocodentro"},
		{"en": "Magma Armor", "it": "Magmascudo"},
		{"en": "Water Veil", "it": "Idrovelo"},
		{"en": "Magnet Pull", "it": "Magnetismo"},
		{"en": "Soundproof", "it": "Antisuono"},
		{"en": "Rain Dish", "it": "Copripioggia"},
		{"en": "Sand Stream", "it": "Sabbiafiume"},
		{"en": "Pressure", "it": "Pressione"},
		{"en": "Thick Fat", "it": "Grassospesso"},
		{"en": "Early Bird", "it": "Sveglialampo"},
		{"en": "Flame Body", "it": "Corpodifuoco"},
		{"en": "Run Away", "it": "Fugafacile"},
		{"en": "Keen Eye", "it": "Sguardofermo"},
		{"en": "Hyper Cutter", "it": "Ipertaglio"},
		{"en": "Pickup", "it": "Raccolta"},
		{"en": "Truant", "it": "Pigrone"},
		{"en": "Hustle", "it": "Tuttafretta"},
		{"en": "Cute Charm", "it": "Incantevole"},
		{"en": "Plus", "it": "Più"},
		{"en": "Minus", "it": "Meno"},
		{"en": "Forecast", "it": "Previsioni"},
		{"en": "Sticky Hold", "it": "Antifurto"},
		{"en": "Shed Skin", "it": "Muta"},
		{"en": "Guts", "it": "Dentistretti"},
		{"en": "Marvel Scale", "it": "Pelledura"},
		{"en": "Liquid Ooze", "it": "Melma"},
		{"en": "Overgrow", "it": "Erbaiuto"},
		{"en": "Blaze", "it": "Aiutofuoco"},
		{"en": "Torrent", "it": "Acquaiuto"},
		{"en": "Swarm", "it": "Aiutinsetto"},
		{"en": "Rock Head", "it": "Testadura"},
		{"en": "Drought", "it": "Siccità"},
		{"en": "Arena Trap", "it": "Trappoarena"},
		{"en": "Vital Spirit", "it": "Spiritovivo"},
		{"en": "White Smoke", "it": "Fumochiaro"},
		{"en": "Pure Power", "it": "Forzapura"},
		{"en": "Shell Armor", "it": "Guscioscudo"},
		{"en": "Air Lock", "it": "Riparo"},
		{"en": "Tangled Feet", "it": "Intricopiedi"},
		{"en": "Motor Drive", "it": "Elettrorapid"},
		{"en": "Rivalry", "it": "Antagonismo"},
		{"en": "Steadfast", "it": "Cuordeciso"},
		{"en": "Snow Cloak", "it": "Mantelneve"},
		{"en": "Gluttony", "it": "Voracità"},
		{"en": "Anger Point", "it": "Grancollera"},
		{"en": "Unburden", "it": "Agiltecnica"},
		{"en": "Heatproof", "it": "Antifuoco"},
		{"en": "Simple", "it": "Disinvoltura"},
		{"en": "Dry Skin", "it": "Pellearsa"},
		{"en": "Download", "it": "Download"},
		{"en": "Iron Fist", "it": "Ferropugno"},
		{"en": "Poison Heal", "it": "Velencura"},
		{"en": "Adaptability", "it": "Adattabilità"},
		{"en": "Skill Link", "it": "Abillegame"},
		{"en": "Hydration", "it": "Idratazione"},
		{"en": "Solar Power", "it": "Solarpotere"},
		{"en": "Quick Feet", "it": "Piedisvelti"},
		{"en": "Normalize", "it": "Normalità"},
		{"en": "Sniper", "it": "Cecchino"},
		{"en": "Magic Guard", "it": "Magicscudo"},
		{"en": "No Guard", "it": "Nullodifesa"},
		{"en": "Stall", "it": "Rallentatore"},
		{"en": "Technician", "it": "Tecnico"},
		{"en": "Leaf Guard", "it": "Fogliamanto"},
		{"en": "Klutz", "it": "Impaccio"},
		{"en": "Mold Breaker", "it": "Rompiforma"},
		{"en": "Super Luck", "it": "Supersorte"},
		{"en": "Aftermath", "it": "Scoppio"},
		{"en": "Anticipation", "it": "Presagio"},
		{"en": "Forewarn", "it": "Premonizione"},
		{"en": "Unaware", "it": "Imprudenza"},
		{"en": "Tinted Lens", "it": "Lentifumé"},
		{"en": "Filter", "it": "Filtro"},
		{"en": "Slow Start", "it": "Lentoinizio"},
		{"en": "Scrappy", "it": "Nervisaldi"},
		{"en": "Storm Drain", "it": "Acquascolo"},
		{"en": "Ice Body", "it": "Corpogelo"},
		{"en": "Solid Rock", "it": "Solidroccia"},
		{"en": "Snow Warning", "it": "Scendineve"},
		{"en": "Honey Gather", "it": "Mielincetta"},
		{"en": "Frisk", "it": "Indagine"},
		{"en": "Reckless", "it": "Temerarietà"},
		{"en": "Multitype", "it": "Multitipo"},
		{"en": "Flower Gift", "it": "Regalfiore"},
		{"en": "Bad Dreams", "it": "Sogniamari"},
		{"en": "Pickpocket", "it": "Arraffalesto"},
		{"en": "Sheer Force", "it": "Forzabruta"},
		{"en": "Contrary", "it": "Inversione"},
		{"en": "Unnerve", "it": "Agitazione"},
		{"en": "Defiant", "it": "Agonismo"},
		{"en": "Defeatist", "it": "Sconforto"},
		{"en": "Cursed Body", "it": "Corpofunesto"},
		{"en": "Healer", "it": "Curacuore"},
		{"en": "Friend Guard", "it": "Amicoscudo"},
		{"en": "Weak Armor", "it": "Sottilguscio"},
		{"en": "Heavy Metal", "it": "Metalpesante"},
		{"en": "Light Metal", "it": "Metalleggero"},
		{"en": "Multiscale", "it": "Multisquame"},
		{"en": "Toxic Boost", "it": "Velenimpeto"},
		{"en": "Flare Boost", "it": "Bruciaimpeto"},
		{"en": "Harvest", "it": "Coglibacche"},
		{"en": "Telepathy", "it": "Telepatia"},
		{"en": "Moody", "it": "Altalena"},
		{"en": "Overcoat", "it": "Copricapo"},
		{"en": "Poison Touch", "it": "Velentocco"},
		{"en": "Regenerator", "it": "Rigenergia"},
		{"en": "Big Pecks", "it": "Pettinfuori"},
		{"en": "Sand Rush", "it": "Remasabbia"},
		{"en": "Wonder Skin", "it": "Splendicute"},
		{"en": "Analytic", "it": "Ponderazione"},
		{"en": "Illusion", "it": "Illusione"},
		{"en": "Imposter", "it": "Sosia"},
		{"en": "Infiltrator", "it": "Intrapasso"},
		{"en": "Mummy", "it": "Mummia"},
		{"en": "Moxie", "it": "Arroganza"},
		{"en": "Justified", "it": "Giustizia"},
		{"en": "Rattled", "it": "Paura"},
		{"en": "Magic Bounce", "it": "Magispecchio"},
		{"en": "Sap Sipper", "it": "Mangiaerba"},
		{"en": "Prankster", "it": "Burla"},
		{"en": "Sand Force", "it": "Silicoforza"},
		{"en": "Iron Barbs", "it": "Spineferrate"},
		{"en": "Zen Mode", "it": "Stato Zen"},
		{"en": "Victory Star", "it": "Vittorstella"},
		{"en": "Turboblaze", "it": "Piroturbina"},
		{"en": "Teravolt", "it": "Teravolt"},
		{"en": "Aroma Veil", "it": "Aromavelo"},
		{"en": "Flower Veil", "it": "Fiorvelo"},
		{"en": "Cheek Pouch", "it": "Guancegonfie"},
		{"en": "Protean", "it": "Mutatipo"},
		{"en": "Fur Coat", "it": "Foltopelo"},
		{"en": "Magician", "it": "Prestigiatore"},
		{"en": "Bulletproof", "it": "Antiproiettile"},
		{"en": "Competitive", "it": "Tenacia"},
		{"en": "Strong Jaw", "it": "Ferromascella"},
		{"en": "Refrigerate", "it": "Pellegelo"},
		{"en": "Sweet Veil", "it": "Dolcevelo"},
		{"en": "Stance Change", "it": "Accendilotta"},
		{"en": "Gale Wings", "it": "Aliraffica"},
		{"en": "Mega Launcher", "it": "Megalancio"},
		{"en": "Grass Pelt", "it": "Peloderba"},
		{"en": "Symbiosis", "it": "Simbiosi"},
		{"en": "Tough Claws", "it": "Unghiedure"},
		{"en": "Pixilate", "it": "Pellefolletto"},
		{"en": "Gooey", "it": "Viscosità"},
		{"en": "Aerilate", "it": "Pellecielo"},
		{"en": "Parental Bond", "it": "Amorefiliale"},
		{"en": "Dark Aura", "it": "Auratetra"},
		{"en": "Fairy Aura", "it": "Aurafolletto"},
		{"en": "Aura Break", "it": "Frangiaura"},
		{"en": "Primordial Sea", "it": "Mare Primordiale"},
		{"en": "Desolate Land", "it": "Terra Estrema"},
		{"en": "Delta Stream", "it": "Flusso Delta"}
	],
	"item": [
		{"en": "Master Ball", "it": "Master Ball"},
		{"en": "Ultra Ball", "it": "Ultra Ball"},
		{"en": "Great Ball", "it": "Mega Ball"},
		{"en": "Poké Ball", "it": "Poké Ball"},
		{"en": "Safari Ball", "it": "Safari Ball"},
		{"en": "Net Ball", "it": "Rete Ball"},
		{"en": "Dive Ball", "it": "Sub Ball"},
		{"en": "Nest Ball", "it": "Minor Ball"},
		{"en": "Repeat Ball", "it": "Bis Ball"},
		{"en": "Timer Ball", "it": "Timer Ball"},
		{"en": "Luxury Ball", "it": "Chic Ball"},
		{"en": "Premier Ball", "it": "Premier Ball"},
		{"en": "Dusk Ball", "it": "Scuro Ball"},
		{"en": "Heal Ball", "it": "Cura Ball"},
		{"en": "Quick Ball", "it": "Velox Ball"},
		{"en": "Cherish Ball", "it": "Pregio Ball"},
		{"en": "Potion", "it": "Pozione"},
		{"en": "Antidote", "it": "Antidoto"},
		{"en": "Burn Heal", "it": "Antiscottatura"},
		{"en": "Ice Heal", "it": "Antigelo"},
		{"en": "Awakening", "it": "Sveglia"},
		{"en": "Paralyze Heal", "it": "Antiparalisi"},
		{"en": "Full Restore", "it": "Ricarica Totale"},
		{"en": "Max Potion", "it": "Pozione Max"},
		{"en": "Hyper Potion", "it": "Iperpozione"},
		{"en": "Super Potion", "it": "Superpozione"},
		{"en": "Full Heal", "it": "Cura Totale"},
		{"en": "Revive", "it": "Revitalizzante"},
		{"en": "Max Revive", "it": "Revitalizz. Max"},
		{"en": "Fresh Water", "it": "Acqua Fresca"},
		{"en": "Soda Pop", "it": "Gassosa"},
		{"en": "Lemonade", "it": "Lemonsucco"},
		{"en": "Moomoo Milk", "it": "Latte Mumu"},
		{"en": "Energy Powder", "it": "Polvenergia"},
		{"en": "Energy Root", "it": "Radicenergia"},
		{"en": "Heal Powder", "it": "Polvocura"},
		{"en": "Revival Herb", "it": "Vitalerba"},
		{"en": "Ether", "it": "Etere"},
		{"en": "Max Ether", "it": "Etere Max"},
		{"en": "Elixir", "it": "Elisir"},
		{"en": "Max Elixir", "it": "Elisir Max"},
		{"en": "Lava Cookie", "it": "Lavottino"},
		{"en": "Berry Juice", "it": "Succodibacca"},
		{"en": "Sacred Ash", "it": "Ceneremagica"},
		{"en": "HP Up", "it": "PS-Su"},
		{"en": "Protein", "it": "Proteina"},
		{"en": "Iron", "it": "Ferro"},
		{"en": "Carbos", "it": "Carburante"},
		{"en": "Calcium", "it": "Calcio"},
		{"en": "Rare Candy", "it": "Caramella Rara"},
		{"en": "PP Up", "it": "PP-Su"},
		{"en": "Zinc", "it": "Zinco"},
		{"en": "PP Max", "it": "PP-Max"},
		{"en": "Old Gateau", "it": "Dolce Gateau"},
		{"en": "Guard Spec.", "it": "Superguardia"},
		{"en": "Dire Hit", "it": "Supercolpo"},
		{"en": "X Attack", "it": "Attacco X"},
		{"en": "X Defense", "it": "Difesa X"},
		{"en": "X Speed", "it": "Velocità X"},
		{"en": "X Accuracy", "it": "Precisione X"},
		{"en": "X Sp. Atk", "it": "Special X"},
		{"en": "X Sp. Def", "it": "Dif. Speciale X"},
		{"en": "Poké Doll", "it": "Poké Bambola"},
		{"en": "Fluffy Tail", "it": "Coda Skitty"},
		{"en": "Blue Flute", "it": "Flauto Blu"},
		{"en": "Yellow Flute", "it": "Flauto Giallo"},
		{"en": "Red Flute", "it": "Flauto Rosso"},
		{"en": "Black Flute", "it": "Flauto Nero"},
		{"en": "White Flute", "it": "Flauto Bianco"},
		{"en": "Shoal Salt", "it": "Sale Ondoso"},
		{"en": "Shoal Shell", "it": "Gusciondoso"},
		{"en": "Red Shard", "it": "Coccio Rosso"},
		{"en": "Blue Shard", "it": "Coccio Blu"},
		{"en": "Yellow Shard", "it": "Coccio Giallo"},
		{"en": "Green Shard", "it": "Coccio Verde"},
		{"en": "Super Repel", "it": "Superrepellente"},
		{"en": "Max Repel", "it": "Repellente Max"},
		{"en": "Escape Rope", "it": "Fune di Fuga"},
		{"en": "Repel", "it": "Repellente"},
		{"en": "Sun Stone", "it": "Pietrasolare"},
		{"en": "Moon Stone", "it": "Pietralunare"},
		{"en": "Fire Stone", "it": "Pietrafocaia"},
		{"en": "Thunder Stone", "it": "Pietratuono"},
		{"en": "Water Stone", "it": "Pietraidrica"},
		{"en": "Leaf Stone", "it": "Pietrafoglia"},
		{"en": "Tiny Mushroom", "it": "Minifungo"},
		{"en": "Big Mushroom", "it": "Grande Fungo"},
		{"en": "Pearl", "it": "Perla"},
		{"en": "Big Pearl", "it": "Grande Perla"},
		{"en": "Stardust", "it": "Polvostella"},
		{"en": "Star Piece", "it": "Pezzo Stella"},
		{"en": "Nugget", "it": "Pepita"},
		{"en": "Heart Scale", "it": "Squama Cuore"},
		{"en": "Honey", "it": "Miele"},
		{"en": "Growth Mulch", "it": "Fertilrapido"},
		{"en": "Damp Mulch", "it": "Fertilidro"},
		{"en": "Stable Mulch", "it": "Fertilsaldo"},
		{"en": "Gooey Mulch", "it": "Fertilcolla"},
		{"en": "Root Fossil", "it": "Radifossile"},
		{"en": "Claw Fossil", "it": "Fossilunghia"},
		{"en": "Helix Fossil", "it": "Helixfossile"},
		{"en": "Dome Fossil", "it": "Domofossile"},
		{"en": "Old Amber", "it": "Ambra Antica"},
		{"en": "Armor Fossil", "it": "Fossilscudo"},
		{"en": "Skull Fossil", "it": "Fossilcranio"},
		{"en": "Rare Bone", "it": "Osso Raro"},
		{"en": "Shiny Stone", "it": "Pietrabrillo"},
		{"en": "Dusk Stone", "it": "Neropietra"},
		{"en": "Dawn Stone", "it": "Pietralbore"},
		{"en": "Oval Stone", "it": "Pietraovale"},
		{"en": "Odd Keystone", "it": "Roccianima"},
		{"en": "Griseous Orb", "it": "Grigiosfera"},
		{"en": "Douse Drive", "it": "Idromodulo"},
		{"en": "Shock Drive", "it": "Voltmodulo"},
		{"en": "Burn Drive", "it": "Piromodulo"},
		{"en": "Chill Drive", "it": "Gelomodulo"},
		{"en": "Sweet Heart", "it": "Dolcecuore"},
		{"en": "Adamant Orb", "it": "Adamasfera"},
		{"en": "Lustrous Orb", "it": "Splendisfera"},
		{"en": "Greet Mail", "it": "Messaggio Inizio"},
		{"en": "Favored Mail", "it": "Messaggio TVB"},
		{"en": "RSVP Mail", "it": "Messaggio Invito"},
		{"en": "Thanks Mail", "it": "Messaggio Grazie"},
		{"en": "Inquiry Mail", "it": "Messaggio Chiedi"},
		{"en": "Like Mail", "it": "Mess. Sugg."},
		{"en": "Reply Mail", "it": "Mess. Risp."},
		{"en": "Bridge Mail S", "it": "Mess. Frec."},
		{"en": "Bridge Mail D", "it": "Mess. Libec."},
		{"en": "Bridge Mail T", "it": "Mess. Prop."},
		{"en": "Bridge Mail V", "it": "Mess. Vill."},
		{"en": "Bridge Mail M", "it": "Mess. Merav."},
		{"en": "Cheri Berry", "it": "Baccaliegia"},
		{"en": "Chesto Berry", "it": "Baccastagna"},
		{"en": "Pecha Berry", "it": "Baccapesca"},
		{"en": "Rawst Berry", "it": "Baccafrago"},
		{"en": "Aspear Berry", "it": "Baccaperina"},
		{"en": "Leppa Berry", "it": "Baccamela"},
		{"en": "Oran Berry", "it": "Baccarancia"},
		{"en": "Persim Berry", "it": "Baccaki"},
		{"en": "Lum Berry", "it": "Baccaprugna"},
		{"en": "Sitrus Berry", "it": "Baccacedro"},
		{"en": "Figy Berry", "it": "Baccafico"},
		{"en": "Wiki Berry", "it": "Baccakiwi"},
		{"en": "Mago Berry", "it": "Baccamango"},
		{"en": "Aguav Berry", "it": "Baccaguava"},
		{"en": "Iapapa Berry", "it": "Baccapaia"},
		{"en": "Razz Berry", "it": "Baccalampon"},
		{"en": "Bluk Berry", "it": "Baccamora"},
		{"en": "Nanab Berry", "it": "Baccabana"},
		{"en": "Wepear Berry", "it": "Baccapera"},
		{"en": "Pinap Berry", "it": "Baccananas"},
		{"en": "Pomeg Berry", "it": "Baccagrana"},
		{"en": "Kelpsy Berry", "it": "Baccalga"},
		{"en": "Qualot Berry", "it": "Baccaloquat"},
		{"en": "Hondew Berry", "it": "Baccamelon"},
		{"en": "Grepa Berry", "it": "Baccauva"},
		{"en": "Tamato Berry", "it": "Baccamodoro"},
		{"en": "Cornn Berry", "it": "Baccavena"},
		{"en": "Magost Berry", "it": "Baccagostan"},
		{"en": "Rabuta Berry", "it": "Baccambutan"},
		{"en": "Nomel Berry", "it": "Baccalemon"},
		{"en": "Spelon Berry", "it": "Baccamelos"},
		{"en": "Pamtre Berry", "it": "Baccapalma"},
		{"en": "Watmel Berry", "it": "Baccacomero"},
		{"en": "Durin Berry", "it": "Baccadurian"},
		{"en": "Belue Berry", "it": "Baccartillo"},
		{"en": "Occa Berry", "it": "Baccacao"},
		{"en": "Passho Berry", "it": "Baccapasflo"},
		{"en": "Wacan Berry", "it": "Baccaparmen"},
		{"en": "Rindo Berry", "it": "Baccarindo"},
		{"en": "Yache Berry", "it": "Baccamoya"},
		{"en": "Chople Berry", "it": "Baccarosmel"},
		{"en": "Kebia Berry", "it": "Baccakebia"},
		{"en": "Shuca Berry", "it": "Baccanaca"},
		{"en": "Coba Berry", "it": "Baccababa"},
		{"en": "Payapa Berry", "it": "Baccapayapa"},
		{"en": "Tanga Berry", "it": "Baccaitan"},
		{"en": "Charti Berry", "it": "Baccaciofo"},
		{"en": "Kasib Berry", "it": "Baccacitrus"},
		{"en": "Haban Berry", "it": "Baccahaban"},
		{"en": "Colbur Berry", "it": "Baccaxan"},
		{"en": "Babiri Berry", "it": "Baccababiri"},
		{"en": "Chilan Berry", "it": "Baccacinlan"},
		{"en": "Liechi Berry", "it": "Baccalici"},
		{"en": "Ganlon Berry", "it": "Baccalongan"},
		{"en": "Salac Berry", "it": "Baccasalak"},
		{"en": "Petaya Berry", "it": "Baccapitaya"},
		{"en": "Apicot Berry", "it": "Baccacocca"},
		{"en": "Lansat Berry", "it": "Baccalangsa"},
		{"en": "Starf Berry", "it": "Baccambola"},
		{"en": "Enigma Berry", "it": "Baccaenigma"},
		{"en": "Micle Berry", "it": "Baccaracolo"},
		{"en": "Custap Berry", "it": "Baccacrela"},
		{"en": "Jaboca Berry", "it": "Baccajaba"},
		{"en": "Rowap Berry", "it": "Baccaroam"},
		{"en": "Bright Powder", "it": "Luminpolvere"},
		{"en": "White Herb", "it": "Erbachiara"},
		{"en": "Macho Brace", "it": "Crescicappa"},
		{"en": "Exp. Share", "it": "Condividi Esp."},
		{"en": "Quick Claw", "it": "Rapidartigli"},
		{"en": "Soothe Bell", "it": "Calmanella"},
		{"en": "Mental Herb", "it": "Mentalerba"},
		{"en": "Choice Band", "it": "Bendascelta"},
		{"en": "King’s Rock", "it": "Roccia di Re"},
		{"en": "Silver Powder", "it": "Argenpolvere"},
		{"en": "Amulet Coin", "it": "Monetamuleto"},
		{"en": "Cleanse Tag", "it": "Velopuro"},
		{"en": "Soul Dew", "it": "Cuorugiada"},
		{"en": "Deep Sea Tooth", "it": "Dente Abissi"},
		{"en": "Deep Sea Scale", "it": "Squamabissi"},
		{"en": "Smoke Ball", "it": "Palla Fumo"},
		{"en": "Everstone", "it": "Pietrastante"},
		{"en": "Focus Band", "it": "Bandana"},
		{"en": "Lucky Egg", "it": "Fortunuovo"},
		{"en": "Scope Lens", "it": "Mirino"},
		{"en": "Metal Coat", "it": "Metalcoperta"},
		{"en": "Leftovers", "it": "Avanzi"},
		{"en": "Dragon Scale", "it": "Squama Drago"},
		{"en": "Light Ball", "it": "Elettropalla"},
		{"en": "Soft Sand", "it": "Sabbia Soffice"},
		{"en": "Hard Stone", "it": "Pietradura"},
		{"en": "Miracle Seed", "it": "Miracolseme"},
		{"en": "Black Glasses", "it": "Occhialineri"},
		{"en": "Black Belt", "it": "Cinturanera"},
		{"en": "Magnet", "it": "Calamita"},
		{"en": "Mystic Water", "it": "Acqua Magica"},
		{"en": "Sharp Beak", "it": "Beccaffilato"},
		{"en": "Poison Barb", "it": "Velenaculeo"},
		{"en": "Never-Melt Ice", "it": "Gelomai"},
		{"en": "Spell Tag", "it": "Spettrotarga"},
		{"en": "Twisted Spoon", "it": "Cucchiaio Torto"},
		{"en": "Charcoal", "it": "Carbonella"},
		{"en": "Dragon Fang", "it": "Dentedidrago"},
		{"en": "Silk Scarf", "it": "Sciarpa Seta"},
		{"en": "Up-Grade", "it": "Upgrade"},
		{"en": "Shell Bell", "it": "Conchinella"},
		{"en": "Sea Incense", "it": "Marearoma"},
		{"en": "Lax Incense", "it": "Distraroma"},
		{"en": "Lucky Punch", "it": "Fortunpugno"},
		{"en": "Metal Powder", "it": "Metalpolvere"},
		{"en": "Thick Club", "it": "Ossospesso"},
		{"en": "Stick", "it": "Gambo"},
		{"en": "Red Scarf", "it": "Fascia Rossa"},
		{"en": "Blue Scarf", "it": "Fascia Blu"},
		{"en": "Pink Scarf", "it": "Fascia Rosa"},
		{"en": "Green Scarf", "it": "Fascia Verde"},
		{"en": "Yellow Scarf", "it": "Fascia Gialla"},
		{"en": "Wide Lens", "it": "Grandelente"},
		{"en": "Muscle Band", "it": "Muscolbanda"},
		{"en": "Wise Glasses", "it": "Saviocchiali"},
		{"en": "Expert Belt", "it": "Abilcintura"},
		{"en": "Light Clay", "it": "Creta Luce"},
		{"en": "Life Orb", "it": "Assorbisfera"},
		{"en": "Power Herb", "it": "Vigorerba"},
		{"en": "Toxic Orb", "it": "Tossicsfera"},
		{"en": "Flame Orb", "it": "Fiammosfera"},
		{"en": "Quick Powder", "it": "Velopolvere"},
		{"en": "Focus Sash", "it": "Focalnastro"},
		{"en": "Zoom Lens", "it": "Zoomlente"},
		{"en": "Metronome", "it": "Plessimetro"},
		{"en": "Iron Ball", "it": "Ferropalla"},
		{"en": "Lagging Tail", "it": "Rallentocoda"},
		{"en": "Destiny Knot", "it": "Destincomune"},
		{"en": "Black Sludge", "it": "Fangopece"},
		{"en": "Icy Rock", "it": "Rocciafredda"},
		{"en": "Smooth Rock", "it": "Roccialiscia"},
		{"en": "Heat Rock", "it": "Rocciacalda"},
		{"en": "Damp Rock", "it": "Rocciaumida"},
		{"en": "Grip Claw", "it": "Presartigli"},
		{"en": "Choice Scarf", "it": "Stolascelta"},
		{"en": "Sticky Barb", "it": "Vischiopunta"},
		{"en": "Power Bracer", "it": "Vigorcerchio"},
		{"en": "Power Belt", "it": "Vigorfascia"},
		{"en": "Power Lens", "it": "Vigorlente"},
		{"en": "Power Band", "it": "Vigorbanda"},
		{"en": "Power Anklet", "it": "Vigorgliera"},
		{"en": "Power Weight", "it": "Vigorpeso"},
		{"en": "Shed Shell", "it": "Disfoguscio"},
		{"en": "Big Root", "it": "Granradice"},
		{"en": "Choice Specs", "it": "Lentiscelta"},
		{"en": "Flame Plate", "it": "Lastrarogo"},
		{"en": "Splash Plate", "it": "Lastraidro"},
		{"en": "Zap Plate", "it": "Lastrasaetta"},
		{"en": "Meadow Plate", "it": "Lastraprato"},
		{"en": "Icicle Plate", "it": "Lastragelo"},
		{"en": "Fist Plate", "it": "Lastrapugno"},
		{"en": "Toxic Plate", "it": "Lastrafiele"},
		{"en": "Earth Plate", "it": "Lastrageo"},
		{"en": "Sky Plate", "it": "Lastracielo"},
		{"en": "Mind Plate", "it": "Lastramente"},
		{"en": "Insect Plate", "it": "Lastrabaco"},
		{"en": "Stone Plate", "it": "Lastrapietra"},
		{"en": "Spooky Plate", "it": "Lastratetra"},
		{"en": "Draco Plate", "it": "Lastradrakon"},
		{"en": "Dread Plate", "it": "Lastratimore"},
		{"en": "Iron Plate", "it": "Lastraferro"},
		{"en": "Odd Incense", "it": "Bizzoaroma"},
		{"en": "Rock Incense", "it": "Roccioaroma"},
		{"en": "Full Incense", "it": "Gonfioaroma"},
		{"en": "Wave Incense", "it": "Ondaroma"},
		{"en": "Rose Incense", "it": "Rosaroma"},
		{"en": "Luck Incense", "it": "Fortunaroma"},
		{"en": "Pure Incense", "it": "Puroaroma"},
		{"en": "Protector", "it": "Copertura"},
		{"en": "Electirizer", "it": "Elettritore"},
		{"en": "Magmarizer", "it": "Magmatore"},
		{"en": "Dubious Disc", "it": "Dubbiodisco"},
		{"en": "Reaper Cloth", "it": "Terrorpanno"},
		{"en": "Razor Claw", "it": "Affilartigli"},
		{"en": "Razor Fang", "it": "Affilodente"},
		{"en": "Explorer Kit", "it": "Esplorokit"},
		{"en": "Loot Sack", "it": "Bottinosacca"},
		{"en": "Rule Book", "it": "Libro Regole"},
		{"en": "Poké Radar", "it": "Poké Radar"},
		{"en": "Point Card", "it": "Scheda Punti"},
		{"en": "Journal", "it": "Agenda"},
		{"en": "Seal Case", "it": "Portabolli"},
		{"en": "Fashion Case", "it": "Scatola Chic"},
		{"en": "Seal Bag", "it": "Bollosacca"},
		{"en": "Pal Pad", "it": "Blocco Amici"},
		{"en": "Works Key", "it": "Turbinchiave"},
		{"en": "Old Charm", "it": "Arcamuleto"},
		{"en": "Galactic Key", "it": "Galachiave"},
		{"en": "Red Chain", "it": "Rossocatena"},
		{"en": "Town Map", "it": "Mappa Città"},
		{"en": "Vs. Seeker", "it": "Cercasfide"},
		{"en": "Coin Case", "it": "Salvadanaio"},
		{"en": "Old Rod", "it": "Amo Vecchio"},
		{"en": "Good Rod", "it": "Amo Buono"},
		{"en": "Super Rod", "it": "Super Amo"},
		{"en": "Sprayduck", "it": "Sprayduck"},
		{"en": "Poffin Case", "it": "Portapoffin"},
		{"en": "Bike", "it": "Bicicletta"},
		{"en": "Suite Key", "it": "Chiave Suite"},
		{"en": "Oak’s Letter", "it": "Lettera Oak"},
		{"en": "Lunar Wing", "it": "Alalunare"},
		{"en": "Member Card", "it": "Scheda Soci"},
		{"en": "Azure Flute", "it": "Flauto Cielo"},
		{"en": "S.S. Ticket", "it": "Biglietto Nave"},
		{"en": "Contest Pass", "it": "Tessera Gare"},
		{"en": "Magma Stone", "it": "Magmapietra"},
		{"en": "Parcel", "it": "Pacco"},
		{"en": "Storage Key", "it": "Depochiave"},
		{"en": "Secret Potion", "it": "Pozione Segreta"},
		{"en": "Vs. Recorder", "it": "Registradati"},
		{"en": "Gracidea", "it": "Gracidea"},
		{"en": "Secret Key", "it": "Chiave Segreta"},
		{"en": "Apricorn Box", "it": "Ghicobox"},
		{"en": "Unown Report", "it": "UnownBloc"},
		{"en": "Berry Pots", "it": "Piantabacche"},
		{"en": "Dowsing Machine", "it": "Ricerca Strum."},
		{"en": "Blue Card", "it": "Carta Blu"},
		{"en": "Slowpoke Tail", "it": "Codaslowpoke"},
		{"en": "Clear Bell", "it": "Campana Chiara"},
		{"en": "Card Key", "it": "Apriporta"},
		{"en": "Basement Key", "it": "Chiave sotterr."},
		{"en": "Squirt Bottle", "it": "Annaffiatoio"},
		{"en": "Red Scale", "it": "Squama Rossa"},
		{"en": "Lost Item", "it": "Strumento perso"},
		{"en": "Pass", "it": "Superpass"},
		{"en": "Machine Part", "it": "Pezzo macch."},
		{"en": "Silver Wing", "it": "Aladargento"},
		{"en": "Rainbow Wing", "it": "Ala d’Iride"},
		{"en": "Mystery Egg", "it": "Uovo Mistero"},
		{"en": "Red Apricorn", "it": "Ghicocca Rossa"},
		{"en": "Blue Apricorn", "it": "Ghicocca Blu"},
		{"en": "Yellow Apricorn", "it": "Ghicocca Gialla"},
		{"en": "Green Apricorn", "it": "Ghicocca Verde"},
		{"en": "Pink Apricorn", "it": "Ghicocca Rosa"},
		{"en": "White Apricorn", "it": "Ghicocca Bianca"},
		{"en": "Black Apricorn", "it": "Ghicocca Nera"},
		{"en": "Fast Ball", "it": "Rapid Ball"},
		{"en": "Level Ball", "it": "Level Ball"},
		{"en": "Lure Ball", "it": "Esca Ball"},
		{"en": "Heavy Ball", "it": "Peso Ball"},
		{"en": "Love Ball", "it": "Love Ball"},
		{"en": "Friend Ball", "it": "Friend Ball"},
		{"en": "Moon Ball", "it": "Luna Ball"},
		{"en": "Sport Ball", "it": "Gara Ball"},
		{"en": "Park Ball", "it": "Parco Ball"},
		{"en": "Photo Album", "it": "Album"},
		{"en": "GB Sounds", "it": "Lettore GB"},
		{"en": "Tidal Bell", "it": "Campana Onda"},
		{"en": "Rage Candy Bar", "it": "Iramella"},
		{"en": "Jade Orb", "it": "Sfera Verde"},
		{"en": "Lock Capsule", "it": "Capsula Scrigno"},
		{"en": "Red Orb", "it": "Gemma rossa"},
		{"en": "Blue Orb", "it": "Gemma blu"},
		{"en": "Enigma Stone", "it": "Misticristal"},
		{"en": "Prism Scale", "it": "Squama Bella"},
		{"en": "Eviolite", "it": "Evolcondensa"},
		{"en": "Float Stone", "it": "Pietralieve"},
		{"en": "Rocky Helmet", "it": "Bitorzolelmo"},
		{"en": "Air Balloon", "it": "Palloncino"},
		{"en": "Red Card", "it": "Cartelrosso"},
		{"en": "Ring Target", "it": "Facilsaglio"},
		{"en": "Binding Band", "it": "Legafascia"},
		{"en": "Absorb Bulb", "it": "Bulbo"},
		{"en": "Cell Battery", "it": "Ricaripila"},
		{"en": "Eject Button", "it": "Pulsantefuga"},
		{"en": "Fire Gem", "it": "Bijoufuoco"},
		{"en": "Water Gem", "it": "Bijouacqua"},
		{"en": "Electric Gem", "it": "Bijouelettro"},
		{"en": "Grass Gem", "it": "Bijouerba"},
		{"en": "Ice Gem", "it": "Bijoughiaccio"},
		{"en": "Fighting Gem", "it": "Bijoulotta"},
		{"en": "Poison Gem", "it": "Bijouveleno"},
		{"en": "Ground Gem", "it": "Bijouterra"},
		{"en": "Flying Gem", "it": "Bijouvolante"},
		{"en": "Psychic Gem", "it": "Bijoupsico"},
		{"en": "Bug Gem", "it": "Bijoucoleottero"},
		{"en": "Rock Gem", "it": "Bijouroccia"},
		{"en": "Ghost Gem", "it": "Bijouspettro"},
		{"en": "Dragon Gem", "it": "Bijoudrago"},
		{"en": "Dark Gem", "it": "Bijoubuio"},
		{"en": "Steel Gem", "it": "Bijouacciaio"},
		{"en": "Normal Gem", "it": "Bijounormale"},
		{"en": "Health Wing", "it": "Piumsalute"},
		{"en": "Muscle Wing", "it": "Piumpotenza"},
		{"en": "Resist Wing", "it": "Piumtutela"},
		{"en": "Genius Wing", "it": "Piumingegno"},
		{"en": "Clever Wing", "it": "Piumintuito"},
		{"en": "Swift Wing", "it": "Piumreazione"},
		{"en": "Pretty Wing", "it": "Piumabella"},
		{"en": "Cover Fossil", "it": "Fossiltappo"},
		{"en": "Plume Fossil", "it": "Fossilpiuma"},
		{"en": "Liberty Pass", "it": "Liberticket"},
		{"en": "Pass Orb", "it": "Passabilia"},
		{"en": "Dream Ball", "it": "Dream Ball"},
		{"en": "Poké Toy", "it": "Pokégingillo"},
		{"en": "Prop Case", "it": "Portagadget"},
		{"en": "Dragon Skull", "it": "Teschio"},
		{"en": "Balm Mushroom", "it": "Profumfungo"},
		{"en": "Big Nugget", "it": "Granpepita"},
		{"en": "Pearl String", "it": "Trittiperla"},
		{"en": "Comet Shard", "it": "Pezzo Cometa"},
		{"en": "Relic Copper", "it": "Soldantico"},
		{"en": "Relic Silver", "it": "Ducatantico"},
		{"en": "Relic Gold", "it": "Doblonantico"},
		{"en": "Relic Vase", "it": "Vasantico"},
		{"en": "Relic Band", "it": "Bracciantico"},
		{"en": "Relic Statue", "it": "Statuantica"},
		{"en": "Relic Crown", "it": "Coronantica"},
		{"en": "Casteliacone", "it": "Conostropoli"},
		{"en": "Dire Hit 2", "it": "Supercolpo 2"},
		{"en": "X Speed 2", "it": "Velocità X-2"},
		{"en": "X Sp. Atk 2", "it": "Special X-2"},
		{"en": "X Sp. Def 2", "it": "Dif. Spec. X-2"},
		{"en": "X Defense 2", "it": "Difesa X-2"},
		{"en": "X Attack 2", "it": "Attacco X-2"},
		{"en": "X Accuracy 2", "it": "Precisione X-2"},
		{"en": "X Speed 3", "it": "Velocità X-3"},
		{"en": "X Sp. Atk 3", "it": "Special X-3"},
		{"en": "X Sp. Def 3", "it": "Dif. Spec. X-3"},
		{"en": "X Defense 3", "it": "Difesa X-3"},
		{"en": "X Attack 3", "it": "Attacco X-3"},
		{"en": "X Accuracy 3", "it": "Precisione X-3"},
		{"en": "X Speed 6", "it": "Velocità X-6"},
		{"en": "X Sp. Atk 6", "it": "Special X-6"},
		{"en": "X Sp. Def 6", "it": "Dif. Spec. X-6"},
		{"en": "X Defense 6", "it": "Difesa X-6"},
		{"en": "X Attack 6", "it": "Attacco X-6"},
		{"en": "X Accuracy 6", "it": "Precisione X-6"},
		{"en": "Ability Urge", "it": "Chiamabilità"},
		{"en": "Item Drop", "it": "Lascioggetto"},
		{"en": "Item Urge", "it": "Chiamoggetto"},
		{"en": "Reset Urge", "it": "Ripristino"},
		{"en": "Dire Hit 3", "it": "Supercolpo 3"},
		{"en": "Light Stone", "it": "Chiarolite"},
		{"en": "Dark Stone", "it": "Scurolite"},
		{"en": "Xtransceiver", "it": "Interpoké"},
		{"en": "Medal Box", "it": "Box Premi"},
		{"en": "DNA Splicers", "it": "Cuneo DNA"},
		{"en": "Permit", "it": "Permesso"},
		{"en": "Oval Charm", "it": "Ovamuleto"},
		{"en": "Shiny Charm", "it": "Cromamuleto"},
		{"en": "Plasma Card", "it": "Carta Plasma"},
		{"en": "Grubby Hanky", "it": "Pezza Sporca"},
		{"en": "Colress Machine", "it": "Acrocongegno"},
		{"en": "Dropped Item", "it": "Oggetto perso"},
		{"en": "Dropped Item", "it": "Oggetto perso"},
		{"en": "Reveal Glass", "it": "Verispecchio"},
		{"en": "Weakness Policy", "it": "Vulneropolizza"},
		{"en": "Assault Vest", "it": "Corpetto assalto"},
		{"en": "Holo Caster", "it": "Holovox"},
		{"en": "Prof’s Letter", "it": "Lettera del Prof"},
		{"en": "Roller Skates", "it": "Pattini"},
		{"en": "Pixie Plate", "it": "Lastraspiritello"},
		{"en": "Ability Capsule", "it": "Capsula abilità"},
		{"en": "Whipped Dream", "it": "Dolcespuma"},
		{"en": "Sachet", "it": "Bustina aromi"},
		{"en": "Luminous Moss", "it": "Muschioluce"},
		{"en": "Snowball", "it": "Palla di neve"},
		{"en": "Safety Goggles", "it": "Visierantisabbia"},
		{"en": "Poké Flute", "it": "Poké Flauto"},
		{"en": "Rich Mulch", "it": "Fertilflorido"},
		{"en": "Surprise Mulch", "it": "Fertilsorpresa"},
		{"en": "Boost Mulch", "it": "Fertilcopioso"},
		{"en": "Amaze Mulch", "it": "Fertilprodigio"},
		{"en": "Gengarite", "it": "Gengarite"},
		{"en": "Gardevoirite", "it": "Gardevoirite"},
		{"en": "Ampharosite", "it": "Ampharosite"},
		{"en": "Venusaurite", "it": "Venusaurite"},
		{"en": "Charizardite X", "it": "Charizardite X"},
		{"en": "Blastoisinite", "it": "Blastoisite"},
		{"en": "Mewtwonite X", "it": "Mewtwoite X"},
		{"en": "Mewtwonite Y", "it": "Mewtwoite Y"},
		{"en": "Blazikenite", "it": "Blazikenite"},
		{"en": "Medichamite", "it": "Medichamite"},
		{"en": "Houndoominite", "it": "Houndoomite"},
		{"en": "Aggronite", "it": "Aggronite"},
		{"en": "Banettite", "it": "Banettite"},
		{"en": "Tyranitarite", "it": "Tyranitarite"},
		{"en": "Scizorite", "it": "Scizorite"},
		{"en": "Pinsirite", "it": "Pinsirite"},
		{"en": "Aerodactylite", "it": "Aerodactylite"},
		{"en": "Lucarionite", "it": "Lucarite"},
		{"en": "Abomasite", "it": "Abomasnowite"},
		{"en": "Kangaskhanite", "it": "Kangaskhanite"},
		{"en": "Gyaradosite", "it": "Gyaradosite"},
		{"en": "Absolite", "it": "Absolite"},
		{"en": "Charizardite Y", "it": "Charizardite Y"},
		{"en": "Alakazite", "it": "Alakazamite"},
		{"en": "Heracronite", "it": "Heracrossite"},
		{"en": "Mawilite", "it": "Mawilite"},
		{"en": "Manectite", "it": "Manectricite"},
		{"en": "Garchompite", "it": "Garchompite"},
		{"en": "Latiasite", "it": "Latiasite"},
		{"en": "Latiosite", "it": "Latiosite"},
		{"en": "Roseli Berry", "it": "Baccarcadè"},
		{"en": "Kee Berry", "it": "Baccalighia"},
		{"en": "Maranga Berry", "it": "Baccapane"},
		{"en": "Sprinklotad", "it": "Irrigalotad"},
		{"en": "Power Plant Pass", "it": "Pass Centrale"},
		{"en": "Mega Ring", "it": "Megacerchio"},
		{"en": "Intriguing Stone", "it": "Sasso suggestivo"},
		{"en": "Common Stone", "it": "Sasso qualsiasi"},
		{"en": "Discount Coupon", "it": "Buono sconto"},
		{"en": "Elevator Key", "it": "Chiave ascensore"},
		{"en": "TMV Pass", "it": "Pass TMV"},
		{"en": "Honor of Kalos", "it": "Emblema di Kalos"},
		{"en": "Adventure Rules", "it": "Guida Avventura"},
		{"en": "Strange Souvenir", "it": "Strano ninnolo"},
		{"en": "Lens Case", "it": "Portalenti"},
		{"en": "Travel Trunk", "it": "Baule per abiti"},
		{"en": "Travel Trunk", "it": "Baule per abiti"},
		{"en": "Lumiose Galette", "it": "Pan di Lumi"},
		{"en": "Shalour Sable", "it": "Yantafrollino"},
		{"en": "Jaw Fossil", "it": "Fossilmascella"},
		{"en": "Sail Fossil", "it": "Fossilpinna"},
		{"en": "Looker Ticket", "it": "Carta Bellocchio"},
		{"en": "Bike", "it": "Bicicletta"},
		{"en": "Holo Caster", "it": "Holovox"},
		{"en": "Fairy Gem", "it": "Bijoufolletto"},
		{"en": "Mega Charm", "it": "Megaciondolo"},
		{"en": "Mega Glove", "it": "Megaguanto"},
		{"en": "Mach Bike", "it": "Bici da corsa"},
		{"en": "Acro Bike", "it": "Bici da cross"},
		{"en": "Wailmer Pail", "it": "Vaso Wailmer"},
		{"en": "Devon Parts", "it": "Merce Devon"},
		{"en": "Soot Sack", "it": "Sacco cenere"},
		{"en": "Basement Key", "it": "Chiave sotterr."},
		{"en": "Pokéblock Kit", "it": "Kit Pokémelle"},
		{"en": "Letter", "it": "Lettera"},
		{"en": "Eon Ticket", "it": "Biglietto Eone"},
		{"en": "Scanner", "it": "Scanner"},
		{"en": "Go-Goggles", "it": "Occhialoni"},
		{"en": "Meteorite", "it": "Meteorite"},
		{"en": "Key to Room 1", "it": "Chiave stanza 1"},
		{"en": "Key to Room 2", "it": "Chiave stanza 2"},
		{"en": "Key to Room 4", "it": "Chiave stanza 4"},
		{"en": "Key to Room 6", "it": "Chiave stanza 6"},
		{"en": "Storage Key", "it": "Chiave magazzino"},
		{"en": "Devon Scope", "it": "Devonscopio"},
		{"en": "S.S. Ticket", "it": "Biglietto Nave"},
		{"en": "Devon Scuba Gear", "it": "Maschera Devon"},
		{"en": "Contest Costume", "it": "Costume Live"},
		{"en": "Contest Costume", "it": "Vestito Live"},
		{"en": "Magma Suit", "it": "Tuta Magma"},
		{"en": "Aqua Suit", "it": "Tuta Idro"},
		{"en": "Pair of Tickets", "it": "Biglietto doppio"},
		{"en": "Mega Bracelet", "it": "Megabracciale"},
		{"en": "Mega Pendant", "it": "Megapendente"},
		{"en": "Mega Glasses", "it": "Megaocchiali"},
		{"en": "Mega Anchor", "it": "Megaancora"},
		{"en": "Mega Stickpin", "it": "Megaspilla"},
		{"en": "Mega Tiara", "it": "Megadiadema"},
		{"en": "Mega Anklet", "it": "Megagambale"},
		{"en": "Meteorite", "it": "Meteorite"},
		{"en": "Swampertite", "it": "Swampertite"},
		{"en": "Sceptilite", "it": "Sceptilite"},
		{"en": "Sablenite", "it": "Sableyite"},
		{"en": "Altarianite", "it": "Altarite"},
		{"en": "Galladite", "it": "Galladite"},
		{"en": "Audinite", "it": "Audinite"},
		{"en": "Metagrossite", "it": "Metagrossite"},
		{"en": "Sharpedonite", "it": "Sharpedite"},
		{"en": "Slowbronite", "it": "Slowbroite"},
		{"en": "Steelixite", "it": "Steelixite"},
		{"en": "Pidgeotite", "it": "Pidgeotite"},
		{"en": "Glalitite", "it": "Glalite"},
		{"en": "Diancite", "it": "Diancite"},
		{"en": "Prison Bottle", "it": "Vaso del vincolo"},
		{"en": "Mega Cuff", "it": "Megapolsiera"},
		{"en": "Cameruptite", "it": "Cameruptite"},
		{"en": "Lopunnite", "it": "Lopunnite"},
		{"en": "Salamencite", "it": "Salamencite"},
		{"en": "Beedrillite", "it": "Beedrillite"},
		{"en": "Meteorite", "it": "Meteorite"},
		{"en": "Meteorite", "it": "Meteorite"},
		{"en": "Key Stone", "it": "Pietrachiave"},
		{"en": "Meteorite Shard", "it": "Framm. meteorite"},
		{"en": "Eon Flute", "it": "Flauto Eone"}
	],
	"move": [
		{"en": "Pound", "it": "Botta"},
		{"en": "Karate Chop", "it": "Colpokarate"},
		{"en": "Double Slap", "it": "Doppiasberla"},
		{"en": "Comet Punch", "it": "Cometapugno"},
		{"en": "Mega Punch", "it": "Megapugno"},
		{"en": "Pay Day", "it": "Giornopaga"},
		{"en": "Fire Punch", "it": "Fuocopugno"},
		{"en": "Ice Punch", "it": "Gelopugno"},
		{"en": "Thunder Punch", "it": "Tuonopugno"},
		{"en": "Scratch", "it": "Graffio"},
		{"en": "Vice Grip", "it": "Presa"},
		{"en": "Guillotine", "it": "Ghigliottina"},
		{"en": "Razor Wind", "it": "Ventagliente"},
		{"en": "Swords Dance", "it": "Danzaspada"},
		{"en": "Cut", "it": "Taglio"},
		{"en": "Gust", "it": "Raffica"},
		{"en": "Wing Attack", "it": "Attacco d’Ala"},
		{"en": "Whirlwind", "it": "Turbine"},
		{"en": "Fly", "it": "Volo"},
		{"en": "Bind", "it": "Legatutto"},
		{"en": "Slam", "it": "Schianto"},
		{"en": "Vine Whip", "it": "Frustata"},
		{"en": "Stomp", "it": "Pestone"},
		{"en": "Double Kick", "it": "Doppiocalcio"},
		{"en": "Mega Kick", "it": "Megacalcio"},
		{"en": "Jump Kick", "it": "Calciosalto"},
		{"en": "Rolling Kick", "it": "Calciorullo"},
		{"en": "Sand Attack", "it": "Turbosabbia"},
		{"en": "Headbutt", "it": "Bottintesta"},
		{"en": "Horn Attack", "it": "Incornata"},
		{"en": "Fury Attack", "it": "Furia"},
		{"en": "Horn Drill", "it": "Perforcorno"},
		{"en": "Tackle", "it": "Azione"},
		{"en": "Body Slam", "it": "Corposcontro"},
		{"en": "Wrap", "it": "Avvolgibotta"},
		{"en": "Take Down", "it": "Riduttore"},
		{"en": "Thrash", "it": "Colpo"},
		{"en": "Double-Edge", "it": "Sdoppiatore"},
		{"en": "Tail Whip", "it": "Colpocoda"},
		{"en": "Poison Sting", "it": "Velenospina"},
		{"en": "Twineedle", "it": "Doppio Ago"},
		{"en": "Pin Missile", "it": "Missilspillo"},
		{"en": "Leer", "it": "Fulmisguardo"},
		{"en": "Bite", "it": "Morso"},
		{"en": "Growl", "it": "Ruggito"},
		{"en": "Roar", "it": "Boato"},
		{"en": "Sing", "it": "Canto"},
		{"en": "Supersonic", "it": "Supersuono"},
		{"en": "Sonic Boom", "it": "Sonicboom"},
		{"en": "Disable", "it": "Inibitore"},
		{"en": "Acid", "it": "Acido"},
		{"en": "Ember", "it": "Braciere"},
		{"en": "Flamethrower", "it": "Lanciafiamme"},
		{"en": "Mist", "it": "Nebbia"},
		{"en": "Water Gun", "it": "Pistolacqua"},
		{"en": "Hydro Pump", "it": "Idropompa"},
		{"en": "Surf", "it": "Surf"},
		{"en": "Ice Beam", "it": "Geloraggio"},
		{"en": "Blizzard", "it": "Bora"},
		{"en": "Psybeam", "it": "Psicoraggio"},
		{"en": "Bubble Beam", "it": "Bollaraggio"},
		{"en": "Aurora Beam", "it": "Raggiaurora"},
		{"en": "Hyper Beam", "it": "Iper Raggio"},
		{"en": "Peck", "it": "Beccata"},
		{"en": "Drill Peck", "it": "Perforbecco"},
		{"en": "Submission", "it": "Sottomissione"},
		{"en": "Low Kick", "it": "Colpo Basso"},
		{"en": "Counter", "it": "Contrattacco"},
		{"en": "Seismic Toss", "it": "Movim. Sismico"},
		{"en": "Strength", "it": "Forza"},
		{"en": "Absorb", "it": "Assorbimento"},
		{"en": "Mega Drain", "it": "Megassorbimento"},
		{"en": "Leech Seed", "it": "Parassiseme"},
		{"en": "Growth", "it": "Crescita"},
		{"en": "Razor Leaf", "it": "Foglielama"},
		{"en": "Solar Beam", "it": "Solarraggio"},
		{"en": "Poison Powder", "it": "Velenpolvere"},
		{"en": "Stun Spore", "it": "Paralizzante"},
		{"en": "Sleep Powder", "it": "Sonnifero"},
		{"en": "Petal Dance", "it": "Petalodanza"},
		{"en": "String Shot", "it": "Millebave"},
		{"en": "Dragon Rage", "it": "Ira di Drago"},
		{"en": "Fire Spin", "it": "Turbofuoco"},
		{"en": "Thunder Shock", "it": "Tuonoshock"},
		{"en": "Thunderbolt", "it": "Fulmine"},
		{"en": "Thunder Wave", "it": "Tuononda"},
		{"en": "Thunder", "it": "Tuono"},
		{"en": "Rock Throw", "it": "Sassata"},
		{"en": "Earthquake", "it": "Terremoto"},
		{"en": "Fissure", "it": "Abisso"},
		{"en": "Dig", "it": "Fossa"},
		{"en": "Toxic", "it": "Tossina"},
		{"en": "Confusion", "it": "Confusione"},
		{"en": "Psychic", "it": "Psichico"},
		{"en": "Hypnosis", "it": "Ipnosi"},
		{"en": "Meditate", "it": "Meditazione"},
		{"en": "Agility", "it": "Agilità"},
		{"en": "Quick Attack", "it": "Attacco Rapido"},
		{"en": "Rage", "it": "Ira"},
		{"en": "Teleport", "it": "Teletrasporto"},
		{"en": "Night Shade", "it": "Ombra Notturna"},
		{"en": "Mimic", "it": "Mimica"},
		{"en": "Screech", "it": "Stridio"},
		{"en": "Double Team", "it": "Doppioteam"},
		{"en": "Recover", "it": "Ripresa"},
		{"en": "Harden", "it": "Rafforzatore"},
		{"en": "Minimize", "it": "Minimizzato"},
		{"en": "Smokescreen", "it": "Muro di Fumo"},
		{"en": "Confuse Ray", "it": "Stordiraggio"},
		{"en": "Withdraw", "it": "Ritirata"},
		{"en": "Defense Curl", "it": "Ricciolscudo"},
		{"en": "Barrier", "it": "Barriera"},
		{"en": "Light Screen", "it": "Schermoluce"},
		{"en": "Haze", "it": "Nube"},
		{"en": "Reflect", "it": "Riflesso"},
		{"en": "Focus Energy", "it": "Focalenergia"},
		{"en": "Bide", "it": "Pazienza"},
		{"en": "Metronome", "it": "Metronomo"},
		{"en": "Mirror Move", "it": "Speculmossa"},
		{"en": "Self-Destruct", "it": "Autodistruzione"},
		{"en": "Egg Bomb", "it": "Uovobomba"},
		{"en": "Lick", "it": "Leccata"},
		{"en": "Smog", "it": "Smog"},
		{"en": "Sludge", "it": "Fango"},
		{"en": "Bone Club", "it": "Ossoclava"},
		{"en": "Fire Blast", "it": "Fuocobomba"},
		{"en": "Waterfall", "it": "Cascata"},
		{"en": "Clamp", "it": "Tenaglia"},
		{"en": "Swift", "it": "Comete"},
		{"en": "Skull Bash", "it": "Capocciata"},
		{"en": "Spike Cannon", "it": "Sparalance"},
		{"en": "Constrict", "it": "Limitazione"},
		{"en": "Amnesia", "it": "Amnesia"},
		{"en": "Kinesis", "it": "Cinèsi"},
		{"en": "Soft-Boiled", "it": "Covauova"},
		{"en": "High Jump Kick", "it": "Calcinvolo"},
		{"en": "Glare", "it": "Sguardo Feroce"},
		{"en": "Dream Eater", "it": "Mangiasogni"},
		{"en": "Poison Gas", "it": "Velenogas"},
		{"en": "Barrage", "it": "Attacco Pioggia"},
		{"en": "Leech Life", "it": "Sanguisuga"},
		{"en": "Lovely Kiss", "it": "Demonbacio"},
		{"en": "Sky Attack", "it": "Aeroattacco"},
		{"en": "Transform", "it": "Trasformazione"},
		{"en": "Bubble", "it": "Bolla"},
		{"en": "Dizzy Punch", "it": "Stordipugno"},
		{"en": "Spore", "it": "Spora"},
		{"en": "Flash", "it": "Flash"},
		{"en": "Psywave", "it": "Psiconda"},
		{"en": "Splash", "it": "Splash"},
		{"en": "Acid Armor", "it": "Scudo Acido"},
		{"en": "Crabhammer", "it": "Martellata"},
		{"en": "Explosion", "it": "Esplosione"},
		{"en": "Fury Swipes", "it": "Sfuriate"},
		{"en": "Bonemerang", "it": "Ossomerang"},
		{"en": "Rest", "it": "Riposo"},
		{"en": "Rock Slide", "it": "Frana"},
		{"en": "Hyper Fang", "it": "Iperzanna"},
		{"en": "Sharpen", "it": "Affilatore"},
		{"en": "Conversion", "it": "Conversione"},
		{"en": "Tri Attack", "it": "Tripletta"},
		{"en": "Super Fang", "it": "Superzanna"},
		{"en": "Slash", "it": "Lacerazione"},
		{"en": "Substitute", "it": "Sostituto"},
		{"en": "Struggle", "it": "Scontro"},
		{"en": "Sketch", "it": "Schizzo"},
		{"en": "Triple Kick", "it": "Triplocalcio"},
		{"en": "Thief", "it": "Furto"},
		{"en": "Spider Web", "it": "Ragnatela"},
		{"en": "Mind Reader", "it": "Leggimente"},
		{"en": "Nightmare", "it": "Incubo"},
		{"en": "Flame Wheel", "it": "Ruotafuoco"},
		{"en": "Snore", "it": "Russare"},
		{"en": "Curse", "it": "Maledizione"},
		{"en": "Flail", "it": "Flagello"},
		{"en": "Conversion 2", "it": "Conversione2"},
		{"en": "Aeroblast", "it": "Aerocolpo"},
		{"en": "Cotton Spore", "it": "Cottonspora"},
		{"en": "Reversal", "it": "Contropiede"},
		{"en": "Spite", "it": "Dispetto"},
		{"en": "Powder Snow", "it": "Polneve"},
		{"en": "Protect", "it": "Protezione"},
		{"en": "Mach Punch", "it": "Pugnorapido"},
		{"en": "Scary Face", "it": "Visotruce"},
		{"en": "Feint Attack", "it": "Finta"},
		{"en": "Sweet Kiss", "it": "Dolcebacio"},
		{"en": "Belly Drum", "it": "Panciamburo"},
		{"en": "Sludge Bomb", "it": "Fangobomba"},
		{"en": "Mud-Slap", "it": "Fangosberla"},
		{"en": "Octazooka", "it": "Octazooka"},
		{"en": "Spikes", "it": "Punte"},
		{"en": "Zap Cannon", "it": "Falcecannone"},
		{"en": "Foresight", "it": "Preveggenza"},
		{"en": "Destiny Bond", "it": "Destinobbligato"},
		{"en": "Perish Song", "it": "Ultimocanto"},
		{"en": "Icy Wind", "it": "Ventogelato"},
		{"en": "Detect", "it": "Individua"},
		{"en": "Bone Rush", "it": "Ossoraffica"},
		{"en": "Lock-On", "it": "Localizza"},
		{"en": "Outrage", "it": "Oltraggio"},
		{"en": "Sandstorm", "it": "Terrempesta"},
		{"en": "Giga Drain", "it": "Gigassorbimento"},
		{"en": "Endure", "it": "Resistenza"},
		{"en": "Charm", "it": "Fascino"},
		{"en": "Rollout", "it": "Rotolamento"},
		{"en": "False Swipe", "it": "Falsofinale"},
		{"en": "Swagger", "it": "Bullo"},
		{"en": "Milk Drink", "it": "Buonlatte"},
		{"en": "Spark", "it": "Scintilla"},
		{"en": "Fury Cutter", "it": "Tagliofuria"},
		{"en": "Steel Wing", "it": "Alacciaio"},
		{"en": "Mean Look", "it": "Malosguardo"},
		{"en": "Attract", "it": "Attrazione"},
		{"en": "Sleep Talk", "it": "Sonnolalia"},
		{"en": "Heal Bell", "it": "Rintoccasana"},
		{"en": "Return", "it": "Ritorno"},
		{"en": "Present", "it": "Regalino"},
		{"en": "Frustration", "it": "Frustrazione"},
		{"en": "Safeguard", "it": "Salvaguardia"},
		{"en": "Pain Split", "it": "Malcomune"},
		{"en": "Sacred Fire", "it": "Magifuoco"},
		{"en": "Magnitude", "it": "Magnitudo"},
		{"en": "Dynamic Punch", "it": "Dinamipugno"},
		{"en": "Megahorn", "it": "Megacorno"},
		{"en": "Dragon Breath", "it": "Dragospiro"},
		{"en": "Baton Pass", "it": "Staffetta"},
		{"en": "Encore", "it": "Ripeti"},
		{"en": "Pursuit", "it": "Inseguimento"},
		{"en": "Rapid Spin", "it": "Rapigiro"},
		{"en": "Sweet Scent", "it": "Profumino"},
		{"en": "Iron Tail", "it": "Codacciaio"},
		{"en": "Metal Claw", "it": "Ferrartigli"},
		{"en": "Vital Throw", "it": "Vitaltiro"},
		{"en": "Morning Sun", "it": "Mattindoro"},
		{"en": "Synthesis", "it": "Sintesi"},
		{"en": "Moonlight", "it": "Lucelunare"},
		{"en": "Hidden Power", "it": "Introforza"},
		{"en": "Cross Chop", "it": "Incrocolpo"},
		{"en": "Twister", "it": "Tornado"},
		{"en": "Rain Dance", "it": "Pioggiadanza"},
		{"en": "Sunny Day", "it": "Giornodisole"},
		{"en": "Crunch", "it": "Sgranocchio"},
		{"en": "Mirror Coat", "it": "Specchiovelo"},
		{"en": "Psych Up", "it": "Psicamisù"},
		{"en": "Extreme Speed", "it": "Extrarapido"},
		{"en": "Ancient Power", "it": "Forzantica"},
		{"en": "Shadow Ball", "it": "Palla Ombra"},
		{"en": "Future Sight", "it": "Divinazione"},
		{"en": "Rock Smash", "it": "Spaccaroccia"},
		{"en": "Whirlpool", "it": "Mulinello"},
		{"en": "Beat Up", "it": "Picchiaduro"},
		{"en": "Fake Out", "it": "Bruciapelo"},
		{"en": "Uproar", "it": "Baraonda"},
		{"en": "Stockpile", "it": "Accumulo"},
		{"en": "Spit Up", "it": "Sfoghenergia"},
		{"en": "Swallow", "it": "Introenergia"},
		{"en": "Heat Wave", "it": "Ondacalda"},
		{"en": "Hail", "it": "Grandine"},
		{"en": "Torment", "it": "Attaccalite"},
		{"en": "Flatter", "it": "Adulazione"},
		{"en": "Will-O-Wisp", "it": "Fuocofatuo"},
		{"en": "Memento", "it": "Memento"},
		{"en": "Facade", "it": "Facciata"},
		{"en": "Focus Punch", "it": "Centripugno"},
		{"en": "Smelling Salts", "it": "Maniereforti"},
		{"en": "Follow Me", "it": "Sonoqui"},
		{"en": "Nature Power", "it": "Naturforza"},
		{"en": "Charge", "it": "Sottocarica"},
		{"en": "Taunt", "it": "Provocazione"},
		{"en": "Helping Hand", "it": "Altruismo"},
		{"en": "Trick", "it": "Raggiro"},
		{"en": "Role Play", "it": "Giocodiruolo"},
		{"en": "Wish", "it": "Desiderio"},
		{"en": "Assist", "it": "Assistente"},
		{"en": "Ingrain", "it": "Radicamento"},
		{"en": "Superpower", "it": "Troppoforte"},
		{"en": "Magic Coat", "it": "Magivelo"},
		{"en": "Recycle", "it": "Riciclo"},
		{"en": "Revenge", "it": "Vendetta"},
		{"en": "Brick Break", "it": "Breccia"},
		{"en": "Yawn", "it": "Sbadiglio"},
		{"en": "Knock Off", "it": "Privazione"},
		{"en": "Endeavor", "it": "Rimonta"},
		{"en": "Eruption", "it": "Eruzione"},
		{"en": "Skill Swap", "it": "Baratto"},
		{"en": "Imprison", "it": "Esclusiva"},
		{"en": "Refresh", "it": "Rinfrescata"},
		{"en": "Grudge", "it": "Rancore"},
		{"en": "Snatch", "it": "Scippo"},
		{"en": "Secret Power", "it": "Forzasegreta"},
		{"en": "Dive", "it": "Sub"},
		{"en": "Arm Thrust", "it": "Sberletese"},
		{"en": "Camouflage", "it": "Camuffamento"},
		{"en": "Tail Glow", "it": "Codadiluce"},
		{"en": "Luster Purge", "it": "Abbagliante"},
		{"en": "Mist Ball", "it": "Foschisfera"},
		{"en": "Feather Dance", "it": "Danzadipiume"},
		{"en": "Teeter Dance", "it": "Strampadanza"},
		{"en": "Blaze Kick", "it": "Calciardente"},
		{"en": "Mud Sport", "it": "Fangata"},
		{"en": "Ice Ball", "it": "Palla Gelo"},
		{"en": "Needle Arm", "it": "Pugnospine"},
		{"en": "Slack Off", "it": "Pigro"},
		{"en": "Hyper Voice", "it": "Granvoce"},
		{"en": "Poison Fang", "it": "Velenodenti"},
		{"en": "Crush Claw", "it": "Tritartigli"},
		{"en": "Blast Burn", "it": "Incendio"},
		{"en": "Hydro Cannon", "it": "Idrocannone"},
		{"en": "Meteor Mash", "it": "Meteorpugno"},
		{"en": "Astonish", "it": "Sgomento"},
		{"en": "Weather Ball", "it": "Palla Clima"},
		{"en": "Aromatherapy", "it": "Aromaterapia"},
		{"en": "Fake Tears", "it": "Falselacrime"},
		{"en": "Air Cutter", "it": "Aerasoio"},
		{"en": "Overheat", "it": "Vampata"},
		{"en": "Odor Sleuth", "it": "Segugio"},
		{"en": "Rock Tomb", "it": "Rocciotomba"},
		{"en": "Silver Wind", "it": "Ventargenteo"},
		{"en": "Metal Sound", "it": "Ferrostrido"},
		{"en": "Grass Whistle", "it": "Meloderba"},
		{"en": "Tickle", "it": "Solletico"},
		{"en": "Cosmic Power", "it": "Cosmoforza"},
		{"en": "Water Spout", "it": "Zampillo"},
		{"en": "Signal Beam", "it": "Segnoraggio"},
		{"en": "Shadow Punch", "it": "Pugnodombra"},
		{"en": "Extrasensory", "it": "Extrasenso"},
		{"en": "Sky Uppercut", "it": "Stramontante"},
		{"en": "Sand Tomb", "it": "Sabbiotomba"},
		{"en": "Sheer Cold", "it": "Purogelo"},
		{"en": "Muddy Water", "it": "Fanghiglia"},
		{"en": "Bullet Seed", "it": "Semitraglia"},
		{"en": "Aerial Ace", "it": "Aeroassalto"},
		{"en": "Icicle Spear", "it": "Gelolancia"},
		{"en": "Iron Defense", "it": "Ferroscudo"},
		{"en": "Block", "it": "Blocco"},
		{"en": "Howl", "it": "Gridodilotta"},
		{"en": "Dragon Claw", "it": "Dragartigli"},
		{"en": "Frenzy Plant", "it": "Radicalbero"},
		{"en": "Bulk Up", "it": "Granfisico"},
		{"en": "Bounce", "it": "Rimbalzo"},
		{"en": "Mud Shot", "it": "Colpodifango"},
		{"en": "Poison Tail", "it": "Velenocoda"},
		{"en": "Covet", "it": "Supplica"},
		{"en": "Volt Tackle", "it": "Locomovolt"},
		{"en": "Magical Leaf", "it": "Fogliamagica"},
		{"en": "Water Sport", "it": "Docciascudo"},
		{"en": "Calm Mind", "it": "Calmamente"},
		{"en": "Leaf Blade", "it": "Fendifoglia"},
		{"en": "Dragon Dance", "it": "Dragodanza"},
		{"en": "Rock Blast", "it": "Cadutamassi"},
		{"en": "Shock Wave", "it": "Ondashock"},
		{"en": "Water Pulse", "it": "Idropulsar"},
		{"en": "Doom Desire", "it": "Obbliderio"},
		{"en": "Psycho Boost", "it": "Psicoslancio"},
		{"en": "Roost", "it": "Trespolo"},
		{"en": "Gravity", "it": "Gravità"},
		{"en": "Miracle Eye", "it": "Miracolvista"},
		{"en": "Wake-Up Slap", "it": "Svegliopacca"},
		{"en": "Hammer Arm", "it": "Martelpugno"},
		{"en": "Gyro Ball", "it": "Vortexpalla"},
		{"en": "Healing Wish", "it": "Curardore"},
		{"en": "Brine", "it": "Acquadisale"},
		{"en": "Natural Gift", "it": "Dononaturale"},
		{"en": "Feint", "it": "Fintoattacco"},
		{"en": "Pluck", "it": "Spennata"},
		{"en": "Tailwind", "it": "Ventoincoda"},
		{"en": "Acupressure", "it": "Acupressione"},
		{"en": "Metal Burst", "it": "Metalscoppio"},
		{"en": "U-turn", "it": "Retromarcia"},
		{"en": "Close Combat", "it": "Zuffa"},
		{"en": "Payback", "it": "Rivincita"},
		{"en": "Assurance", "it": "Garanzia"},
		{"en": "Embargo", "it": "Divieto"},
		{"en": "Fling", "it": "Lancio"},
		{"en": "Psycho Shift", "it": "Psicotrasfer"},
		{"en": "Trump Card", "it": "Asso"},
		{"en": "Heal Block", "it": "Anticura"},
		{"en": "Wring Out", "it": "Strizzata"},
		{"en": "Power Trick", "it": "Ingannoforza"},
		{"en": "Gastro Acid", "it": "Gastroacido"},
		{"en": "Lucky Chant", "it": "Fortuncanto"},
		{"en": "Me First", "it": "Precedenza"},
		{"en": "Copycat", "it": "Copione"},
		{"en": "Power Swap", "it": "Barattoforza"},
		{"en": "Guard Swap", "it": "Barattoscudo"},
		{"en": "Punishment", "it": "Punizione"},
		{"en": "Last Resort", "it": "Ultimascelta"},
		{"en": "Worry Seed", "it": "Affannoseme"},
		{"en": "Sucker Punch", "it": "Sbigoattacco"},
		{"en": "Toxic Spikes", "it": "Fielepunte"},
		{"en": "Heart Swap", "it": "Cuorbaratto"},
		{"en": "Aqua Ring", "it": "Acquanello"},
		{"en": "Magnet Rise", "it": "Magnetascesa"},
		{"en": "Flare Blitz", "it": "Fuococarica"},
		{"en": "Force Palm", "it": "Palmoforza"},
		{"en": "Aura Sphere", "it": "Forzasfera"},
		{"en": "Rock Polish", "it": "Lucidatura"},
		{"en": "Poison Jab", "it": "Velenpuntura"},
		{"en": "Dark Pulse", "it": "Neropulsar"},
		{"en": "Night Slash", "it": "Nottesferza"},
		{"en": "Aqua Tail", "it": "Idrondata"},
		{"en": "Seed Bomb", "it": "Semebomba"},
		{"en": "Air Slash", "it": "Eterelama"},
		{"en": "X-Scissor", "it": "Forbice X"},
		{"en": "Bug Buzz", "it": "Ronzio"},
		{"en": "Dragon Pulse", "it": "Dragopulsar"},
		{"en": "Dragon Rush", "it": "Dragofuria"},
		{"en": "Power Gem", "it": "Gemmoforza"},
		{"en": "Drain Punch", "it": "Assorbipugno"},
		{"en": "Vacuum Wave", "it": "Vuotonda"},
		{"en": "Focus Blast", "it": "Focalcolpo"},
		{"en": "Energy Ball", "it": "Energipalla"},
		{"en": "Brave Bird", "it": "Baldeali"},
		{"en": "Earth Power", "it": "Geoforza"},
		{"en": "Switcheroo", "it": "Rapidscambio"},
		{"en": "Giga Impact", "it": "Gigaimpatto"},
		{"en": "Nasty Plot", "it": "Congiura"},
		{"en": "Bullet Punch", "it": "Pugnoscarica"},
		{"en": "Avalanche", "it": "Slavina"},
		{"en": "Ice Shard", "it": "Geloscheggia"},
		{"en": "Shadow Claw", "it": "Ombrartigli"},
		{"en": "Thunder Fang", "it": "Fulmindenti"},
		{"en": "Ice Fang", "it": "Gelodenti"},
		{"en": "Fire Fang", "it": "Rogodenti"},
		{"en": "Shadow Sneak", "it": "Furtivombra"},
		{"en": "Mud Bomb", "it": "Pantanobomba"},
		{"en": "Psycho Cut", "it": "Psicotaglio"},
		{"en": "Zen Headbutt", "it": "Cozzata Zen"},
		{"en": "Mirror Shot", "it": "Cristalcolpo"},
		{"en": "Flash Cannon", "it": "Cannonflash"},
		{"en": "Rock Climb", "it": "Scalaroccia"},
		{"en": "Defog", "it": "Scacciabruma"},
		{"en": "Trick Room", "it": "Distortozona"},
		{"en": "Draco Meteor", "it": "Dragobolide"},
		{"en": "Discharge", "it": "Scarica"},
		{"en": "Lava Plume", "it": "Lavasbuffo"},
		{"en": "Leaf Storm", "it": "Verdebufera"},
		{"en": "Power Whip", "it": "Vigorcolpo"},
		{"en": "Rock Wrecker", "it": "Devastomasso"},
		{"en": "Cross Poison", "it": "Velenocroce"},
		{"en": "Gunk Shot", "it": "Sporcolancio"},
		{"en": "Iron Head", "it": "Metaltestata"},
		{"en": "Magnet Bomb", "it": "Bombagnete"},
		{"en": "Stone Edge", "it": "Pietrataglio"},
		{"en": "Captivate", "it": "Incanto"},
		{"en": "Stealth Rock", "it": "Levitoroccia"},
		{"en": "Grass Knot", "it": "Laccioerboso"},
		{"en": "Chatter", "it": "Schiamazzo"},
		{"en": "Judgment", "it": "Giudizio"},
		{"en": "Bug Bite", "it": "Coleomorso"},
		{"en": "Charge Beam", "it": "Raggioscossa"},
		{"en": "Wood Hammer", "it": "Mazzuolegno"},
		{"en": "Aqua Jet", "it": "Acquagetto"},
		{"en": "Attack Order", "it": "Comandourto"},
		{"en": "Defend Order", "it": "Comandoscudo"},
		{"en": "Heal Order", "it": "Comandocura"},
		{"en": "Head Smash", "it": "Zuccata"},
		{"en": "Double Hit", "it": "Doppiosmash"},
		{"en": "Roar of Time", "it": "Fragortempo"},
		{"en": "Spacial Rend", "it": "Fendispazio"},
		{"en": "Lunar Dance", "it": "Lunardanza"},
		{"en": "Crush Grip", "it": "Sbriciolmano"},
		{"en": "Magma Storm", "it": "Magmaclisma"},
		{"en": "Dark Void", "it": "Vuototetro"},
		{"en": "Seed Flare", "it": "Infuriaseme"},
		{"en": "Ominous Wind", "it": "Funestovento"},
		{"en": "Shadow Force", "it": "Oscurotuffo"},
		{"en": "Hone Claws", "it": "Unghiaguzze"},
		{"en": "Wide Guard", "it": "Bodyguard"},
		{"en": "Guard Split", "it": "Paridifesa"},
		{"en": "Power Split", "it": "Pariattacco"},
		{"en": "Wonder Room", "it": "Mirabilzona"},
		{"en": "Psyshock", "it": "Psicoshock"},
		{"en": "Venoshock", "it": "Velenoshock"},
		{"en": "Autotomize", "it": "Sganciapesi"},
		{"en": "Rage Powder", "it": "Polverabbia"},
		{"en": "Telekinesis", "it": "Telecinesi"},
		{"en": "Magic Room", "it": "Magicozona"},
		{"en": "Smack Down", "it": "Abbattimento"},
		{"en": "Storm Throw", "it": "Tempestretta"},
		{"en": "Flame Burst", "it": "Pirolancio"},
		{"en": "Sludge Wave", "it": "Fangonda"},
		{"en": "Quiver Dance", "it": "Eledanza"},
		{"en": "Heavy Slam", "it": "Pesobomba"},
		{"en": "Synchronoise", "it": "Sincrumore"},
		{"en": "Electro Ball", "it": "Energisfera"},
		{"en": "Soak", "it": "Inondazione"},
		{"en": "Flame Charge", "it": "Nitrocarica"},
		{"en": "Coil", "it": "Arrotola"},
		{"en": "Low Sweep", "it": "Calciobasso"},
		{"en": "Acid Spray", "it": "Acidobomba"},
		{"en": "Foul Play", "it": "Ripicca"},
		{"en": "Simple Beam", "it": "Ondisinvolta"},
		{"en": "Entrainment", "it": "Saltamicizia"},
		{"en": "After You", "it": "Cortesia"},
		{"en": "Round", "it": "Coro"},
		{"en": "Echoed Voice", "it": "Echeggiavoce"},
		{"en": "Chip Away", "it": "Insidia"},
		{"en": "Clear Smog", "it": "Pulifumo"},
		{"en": "Stored Power", "it": "Veicolaforza"},
		{"en": "Quick Guard", "it": "Anticipo"},
		{"en": "Ally Switch", "it": "Cambiaposto"},
		{"en": "Scald", "it": "Idrovampata"},
		{"en": "Shell Smash", "it": "Gettaguscio"},
		{"en": "Heal Pulse", "it": "Ondasana"},
		{"en": "Hex", "it": "Sciagura"},
		{"en": "Sky Drop", "it": "Cadutalibera"},
		{"en": "Shift Gear", "it": "Cambiomarcia"},
		{"en": "Circle Throw", "it": "Ribaltiro"},
		{"en": "Incinerate", "it": "Bruciatutto"},
		{"en": "Quash", "it": "Spintone"},
		{"en": "Acrobatics", "it": "Acrobazia"},
		{"en": "Reflect Type", "it": "Riflettipo"},
		{"en": "Retaliate", "it": "Nemesi"},
		{"en": "Final Gambit", "it": "Azzardo"},
		{"en": "Bestow", "it": "Cediregalo"},
		{"en": "Inferno", "it": "Marchiatura"},
		{"en": "Water Pledge", "it": "Acquapatto"},
		{"en": "Fire Pledge", "it": "Fiammapatto"},
		{"en": "Grass Pledge", "it": "Erbapatto"},
		{"en": "Volt Switch", "it": "Invertivolt"},
		{"en": "Struggle Bug", "it": "Entomoblocco"},
		{"en": "Bulldoze", "it": "Battiterra"},
		{"en": "Frost Breath", "it": "Alitogelido"},
		{"en": "Dragon Tail", "it": "Codadrago"},
		{"en": "Work Up", "it": "Cuordileone"},
		{"en": "Electroweb", "it": "Elettrotela"},
		{"en": "Wild Charge", "it": "Sprizzalampo"},
		{"en": "Drill Run", "it": "Giravvita"},
		{"en": "Dual Chop", "it": "Doppiocolpo"},
		{"en": "Heart Stamp", "it": "Cuorestampo"},
		{"en": "Horn Leech", "it": "Legnicorno"},
		{"en": "Sacred Sword", "it": "Spadasolenne"},
		{"en": "Razor Shell", "it": "Conchilama"},
		{"en": "Heat Crash", "it": "Marchiafuoco"},
		{"en": "Leaf Tornado", "it": "Vorticerba"},
		{"en": "Steamroller", "it": "Rulloduro"},
		{"en": "Cotton Guard", "it": "Cotonscudo"},
		{"en": "Night Daze", "it": "Urtoscuro"},
		{"en": "Psystrike", "it": "Psicobotta"},
		{"en": "Tail Slap", "it": "Spazzasberla"},
		{"en": "Hurricane", "it": "Tifone"},
		{"en": "Head Charge", "it": "Ricciolata"},
		{"en": "Gear Grind", "it": "Ingracolpo"},
		{"en": "Searing Shot", "it": "Sparafuoco"},
		{"en": "Techno Blast", "it": "Tecnobotto"},
		{"en": "Relic Song", "it": "Cantoantico"},
		{"en": "Secret Sword", "it": "Spadamistica"},
		{"en": "Glaciate", "it": "Gelamondo"},
		{"en": "Bolt Strike", "it": "Lucesiluro"},
		{"en": "Blue Flare", "it": "Fuocoblu"},
		{"en": "Fiery Dance", "it": "Voldifuoco"},
		{"en": "Freeze Shock", "it": "Elettrogelo"},
		{"en": "Ice Burn", "it": "Vampagelida"},
		{"en": "Snarl", "it": "Urlorabbia"},
		{"en": "Icicle Crash", "it": "Scagliagelo"},
		{"en": "V-create", "it": "Generatore V"},
		{"en": "Fusion Flare", "it": "Incrofiamma"},
		{"en": "Fusion Bolt", "it": "Incrotuono"},
		{"en": "Flying Press", "it": "Schiacciatuffo"},
		{"en": "Mat Block", "it": "Ribaltappeto"},
		{"en": "Belch", "it": "Rutto"},
		{"en": "Rototiller", "it": "Aracampo"},
		{"en": "Sticky Web", "it": "Rete Vischiosa"},
		{"en": "Fell Stinger", "it": "Pungiglione"},
		{"en": "Phantom Force", "it": "Spettrotuffo"},
		{"en": "Trick-or-Treat", "it": "Halloween"},
		{"en": "Noble Roar", "it": "Urlo"},
		{"en": "Ion Deluge", "it": "Pioggiaplasma"},
		{"en": "Parabolic Charge", "it": "Caricaparabola"},
		{"en": "Forest’s Curse", "it": "Boscomalocchio"},
		{"en": "Petal Blizzard", "it": "Fiortempesta"},
		{"en": "Freeze-Dry", "it": "Liofilizzazione"},
		{"en": "Disarming Voice", "it": "Incantavoce"},
		{"en": "Parting Shot", "it": "Monito"},
		{"en": "Topsy-Turvy", "it": "Sottosopra"},
		{"en": "Draining Kiss", "it": "Assorbibacio"},
		{"en": "Crafty Shield", "it": "Truccodifesa"},
		{"en": "Flower Shield", "it": "Fiordifesa"},
		{"en": "Grassy Terrain", "it": "Campo Erboso"},
		{"en": "Misty Terrain", "it": "Campo Nebbioso"},
		{"en": "Electrify", "it": "Elettrocontagio"},
		{"en": "Play Rough", "it": "Carineria"},
		{"en": "Fairy Wind", "it": "Vento di Fata"},
		{"en": "Moonblast", "it": "Forza Lunare"},
		{"en": "Boomburst", "it": "Ondaboato"},
		{"en": "Fairy Lock", "it": "Blocco Fatato"},
		{"en": "King’s Shield", "it": "Scudo Reale"},
		{"en": "Play Nice", "it": "Simpatia"},
		{"en": "Confide", "it": "Confidenza"},
		{"en": "Diamond Storm", "it": "Diamantempesta"},
		{"en": "Steam Eruption", "it": "Vaporscoppio"},
		{"en": "Hyperspace Hole", "it": "Forodimensionale"},
		{"en": "Water Shuriken", "it": "Acqualame"},
		{"en": "Mystical Fire", "it": "Magifiamma"},
		{"en": "Spiky Shield", "it": "Agodifesa"},
		{"en": "Aromatic Mist", "it": "Nebularoma"},
		{"en": "Eerie Impulse", "it": "Elettromistero"},
		{"en": "Venom Drench", "it": "Velenotrappola"},
		{"en": "Powder", "it": "Pulviscoppio"},
		{"en": "Geomancy", "it": "Geocontrollo"},
		{"en": "Magnetic Flux", "it": "Controllo Polare"},
		{"en": "Happy Hour", "it": "Cuccagna"},
		{"en": "Electric Terrain", "it": "Campo Elettrico"},
		{"en": "Dazzling Gleam", "it": "Magibrillio"},
		{"en": "Celebrate", "it": "Auguri"},
		{"en": "Hold Hands", "it": "Mano nella Mano"},
		{"en": "Baby-Doll Eyes", "it": "Occhioni Teneri"},
		{"en": "Nuzzle", "it": "Elettrococcola"},
		{"en": "Hold Back", "it": "Riguardo"},
		{"en": "Infestation", "it": "Assillo"},
		{"en": "Power-Up Punch", "it": "Crescipugno"},
		{"en": "Oblivion Wing", "it": "Ali del Fato"},
		{"en": "Thousand Arrows", "it": "Mille Frecce"},
		{"en": "Thousand Waves", "it": "Mille Onde"},
		{"en": "Land’s Wrath", "it": "Forza Tellurica"},
		{"en": "Light of Ruin", "it": "Luce Nefasta"},
		{"en": "Origin Pulse", "it": "Primopulsar"},
		{"en": "Precipice Blades", "it": "Spade Telluriche"},
		{"en": "Dragon Ascent", "it": "Ascesa del Drago"},
		{"en": "Hyperspace Fury", "it": "Urtodimensionale"}
	],
	"nature": [
		{"en": "Hardy", "it": "Ardita"},
		{"en": "Lonely", "it": "Schiva"},
		{"en": "Brave", "it": "Audace"},
		{"en": "Adamant", "it": "Decisa"},
		{"en": "Naughty", "it": "Birbona"},
		{"en": "Bold", "it": "Sicura"},
		{"en": "Docile", "it": "Docile"},
		{"en": "Relaxed", "it": "Placida"},
		{"en": "Impish", "it": "Scaltra"},
		{"en": "Lax", "it": "Fiacca"},
		{"en": "Timid", "it": "Timida"},
		{"en": "Hasty", "it": "Lesta"},
		{"en": "Serious", "it": "Seria"},
		{"en": "Jolly", "it": "Allegra"},
		{"en": "Naive", "it": "Ingenua"},
		{"en": "Modest", "it": "Modesta"},
		{"en": "Mild", "it": "Mite"},
		{"en": "Quiet", "it": "Quieta"},
		{"en": "Bashful", "it": "Ritrosa"},
		{"en": "Rash", "it": "Ardente"},
		{"en": "Calm", "it": "Calma"},
		{"en": "Gentle", "it": "Gentile"},
		{"en": "Sassy", "it": "Vivace"},
		{"en": "Careful", "it": "Cauta"},
		{"en": "Quirky", "it": "Furba"}
	]
};